// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1fFsGwqYgSUalaHfimCJvWgf3s7JCaSQ',
    appId: '1:889936606967:web:6e38f2c2ef941e831a85f2',
    messagingSenderId: '889936606967',
    projectId: 'pandemonium-dbffa',
    authDomain: 'pandemonium-dbffa.firebaseapp.com',
    storageBucket: 'pandemonium-dbffa.appspot.com',
    measurementId: 'G-YQ25PFQNST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC6rm4JN7Z3qtRcHxlOdjDceOne3Poajo',
    appId: '1:889936606967:android:ee6a1a4cf3db90e91a85f2',
    messagingSenderId: '889936606967',
    projectId: 'pandemonium-dbffa',
    storageBucket: 'pandemonium-dbffa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgLdPi7QVWXWK9bcl70o-0JOgy94yMpk8',
    appId: '1:889936606967:ios:9e0a0f34bf1014a81a85f2',
    messagingSenderId: '889936606967',
    projectId: 'pandemonium-dbffa',
    storageBucket: 'pandemonium-dbffa.appspot.com',
    iosBundleId: 'com.example.pandemonium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgLdPi7QVWXWK9bcl70o-0JOgy94yMpk8',
    appId: '1:889936606967:ios:9e0a0f34bf1014a81a85f2',
    messagingSenderId: '889936606967',
    projectId: 'pandemonium-dbffa',
    storageBucket: 'pandemonium-dbffa.appspot.com',
    iosBundleId: 'com.example.pandemonium',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1fFsGwqYgSUalaHfimCJvWgf3s7JCaSQ',
    appId: '1:889936606967:web:59bb62b4fffaa40d1a85f2',
    messagingSenderId: '889936606967',
    projectId: 'pandemonium-dbffa',
    authDomain: 'pandemonium-dbffa.firebaseapp.com',
    storageBucket: 'pandemonium-dbffa.appspot.com',
    measurementId: 'G-GW1CZ6XCFE',
  );

}